### PR TITLE
Added a limestone retexture / new stone textures

### PR DESCRIPTION
**Pull request by MrBurd**
Birdstone. Bit lighter than limestone while still not as eye-burning white as marble/diorite.

### CODE REVIEW

**Comment by Drullkus** [comment]
I'm the artist and I approve of this.

**Comment by TheCricket** [comment]
is this limestone or a new block, because I just see birdstone

**Comment by Drullkus** [comment]
Limestone

**Comment by TheCricket** [comment]
do we really have it called birdstone in code, I have never known this

**Comment by MrBurd** [comment]
placeholder name. wasn't sure what to call but apparently it's limestone still

**Pull request merged**
